language: go

go:
  - 1.6
  - 1.5
  - 1.4
  - 1.3
  - release
  - tip

before_install:
  - go get -u github.com/nbio/st
  - go get -u gopkg.in/check.v1
  - go get -u gopkg.in/vinci-proxy/layer.v0
  - go get -u gopkg.in/vinci-proxy/vinci.v0
  - go get -u golang.org/x/net/websocket
  - go get -u github.com/vulcand/oxy/testutils
  - go get -u -v github.com/axw/gocov/gocov
  - go get -u -v github.com/mattn/goveralls
  - '[[ $(go version) == *1.[5-9]+* ]] && go get -u -v github.com/golang/lint/golint; exit 0'

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - '[[ $(go version) == *1.[5-9]+* ]] && diff -u <(echo -n) <(golint ./); exit 0'
  - go test -v -race ./...
  - go test -v -race -covermode=atomic -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
