language: go

go:
  - 1.6
  - 1.5
  - tip

before_install:
  - go get github.com/nbio/st
  - go get -u gopkg.in/vinxi/context.v0
  - go get -u gopkg.in/vinxi/utils.v0
  - go get -u gopkg.in/check.v1
  - go get -u golang.org/x/net/websocket
  - go get -u github.com/vulcand/oxy/testutils
  - go get -u -v github.com/axw/gocov/gocov
  - go get -u -v github.com/mattn/goveralls
  - go get -u -v github.com/golang/lint/golint

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./)
  - diff -u <(echo -n) <(golint ./)
  - go test -v -race -covermode=atomic -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
